# Generated by Django 4.1.6 on 2023-03-07 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_task_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
