# Generated by Django 4.1.6 on 2023-03-07 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_task_assigned_alter_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
